# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bwt_design/bwt_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design || ORIG_REF_NAME==bwt_design} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_processing_system7_0_0/bwt_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_processing_system7_0_0 || ORIG_REF_NAME==bwt_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_bwt_ip_0_0/bwt_design_bwt_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_bwt_ip_0_0 || ORIG_REF_NAME==bwt_design_bwt_ip_0_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_xbar_0/bwt_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_xbar_0 || ORIG_REF_NAME==bwt_design_xbar_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_ps7_0_axi_periph_0/bwt_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==bwt_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_rst_ps7_0_100M_0/bwt_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==bwt_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_axi_gpio_0_0/bwt_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_axi_gpio_0_0 || ORIG_REF_NAME==bwt_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bwt_design/ip/bwt_design_auto_pc_0/bwt_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bwt_design_auto_pc_0 || ORIG_REF_NAME==bwt_design_auto_pc_0} -quiet] -quiet

# XDC: bd/bwt_design/bwt_design_ooc.xdc
