# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.runs/synth_1/.Xil/Vivado-19660-DESKTOP-64JSPKI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/c923
    d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/ec67/hdl
  } {
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/MM_top.sv
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/bwt_top.sv
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/fifo.sv
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/merge_sort_top.sv
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/sort2elem.sv
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/src/sort_arrays.sv
      D:/Programy/Vivado2019_1/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Programy/Vivado2019_1/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/c923
    d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/ec67/hdl
  } {
      D:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/hdl/mb_design_wrapper.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/hdl/bwt_ip_v1_0_S00_AXI.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/49cf/hdl/bwt_ip_v1_0.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_bwt_ip_0_0_1/synth/mb_design_bwt_ip_0_0.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_clk_wiz_1_0_1/mb_design_clk_wiz_1_0_clk_wiz.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_clk_wiz_1_0_1/mb_design_clk_wiz_1_0.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_xbar_0_1/synth/mb_design_xbar_0.v
      D:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/synth/mb_design.v
    }
      rt::read_vhdl -lib microblaze_v11_0_1 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/f8c3/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_microblaze_0_0_1/synth/mb_design_microblaze_0_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_input_string_char_0/synth/mb_design_input_string_char_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_output_string_char_0/synth/mb_design_output_string_char_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_dlmb_v10_0_1/synth/mb_design_dlmb_v10_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_v10_0_1/synth/mb_design_ilmb_v10_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_dlmb_bram_if_cntlr_0_1/synth/mb_design_dlmb_bram_if_cntlr_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_0_1/synth/mb_design_ilmb_bram_if_cntlr_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_lmb_bram_0_1/synth/mb_design_lmb_bram_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_mdm_1_0_1/synth/mb_design_mdm_1_0.vhd
      d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0_1/synth/mb_design_rst_clk_wiz_1_100M_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_21 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/9c6e/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_v10_v3_0_9 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_16 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/6335/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_3 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/c001/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib mdm_v3_2_16 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/550e/hdl/mdm_v3_2_vh_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_4 d:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.srcs/sources_1/bd/mb_design/ipshared/1f5a/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm D:/Programy/Vivado2019_1/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mb_design_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/MTM/semestr8/SDUP_BWT/BWT/BWT_TEST/bwt_test.runs/synth_1/.Xil/Vivado-19660-DESKTOP-64JSPKI/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
