@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Sep 05 16:04:43 +0200 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim bwt_top_tb_func_synth -key {Post-Synthesis:sim_1:Functional:bwt_top_tb} -tclbatch bwt_top_tb.tcl -protoinst "protoinst_files/bwt_design.protoinst" -view D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/bwt_top_tb_func_synth.wcfg -log simulate.log"
call xsim  bwt_top_tb_func_synth -key {Post-Synthesis:sim_1:Functional:bwt_top_tb} -tclbatch bwt_top_tb.tcl -protoinst "protoinst_files/bwt_design.protoinst" -view D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/bwt_top_tb_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
