webtalk_init -webtalk_dir D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/zynq_bwt_v2.sim/sim_1/synth/func/xsim/xsim.dir/bwt_top_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep  5 16:04:42 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9daa3f2b-3c53-4a9b-94ee-36bf0b615bc0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5055aa20fb234c989dd49bcef5a3779e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "8" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "236 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "54 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "859" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "160" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.81_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "66976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3174735079 -regid "211456598_0_0_068" -xml D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/zynq_bwt_v2.sim/sim_1/synth/func/xsim/xsim.dir/bwt_top_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/zynq_bwt_v2.sim/sim_1/synth/func/xsim/xsim.dir/bwt_top_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/MTM/semestr8/SDUP_BWT/BWT_3/BWT/Zynq_bwt_v2/zynq_bwt_v2/zynq_bwt_v2.sim/sim_1/synth/func/xsim/xsim.dir/bwt_top_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
